server:
  address: 0.0.0.0
  port: 8084

spring:
  application:
    name: undergraduate-academic-administration
  security:
    user:
      name: lyj
      password: lyj
  datasource:
    url: jdbc:mysql://localhost:3307/fjxgwzd_eduma
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  debug: true

mybatis:
  type-aliases-package: com.fjxgwzd.undergraduateacademicadministration.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  jackson:
    default-property-inclusion: non_null  # 防止返回值为null的属性
  debug: true