services:
  mysql:
    image: 'mysql:8.0.31'
    environment:
      - 'MYSQL_DATABASE=fjxgwzd_eduma'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
      - ./sql-init:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis-data:/data
    networks:
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  backend: