

#
#mybatis:
#  type-aliases-package: com.fjxgwzd.teacherresourcesharing.entity
#  mapper-locations: classpath:mapper/*.xml
##    mapper-locations: file:/Users/liangyejing/IdeaProjects/education-management-platform/teacher-resource-sharing/src/main/resources/mapper/ChapterMapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  jackson:
#    default-property-inclusion: non_null  # 防止返回值为null的属性
#  debug: true
#
#server:
#  port: 8082
#  address: 0.0.0.0

#minio:
#  endpoint: http://8.130.106.248:9000
#  access-key: minioadmin
#  secret-key: minioadmin
#  bucket-name: system

